spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/maamin11/springcloud-config.git
          search-paths: testfile
          username:
          password:
      label: master
server:
  port: 8769
# 注册中心的地址
eureka:
  client:
    serviceUrl:
     defaultZone: http://localhost:8761/eureka/